// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMulticel.WebAPI.Data;

namespace ProMulticel.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProMulticel.WebAPI.Model.Formulario", b =>
                {
                    b.Property<int>("FormularioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataFormulario");

                    b.Property<string>("Filial");

                    b.Property<string>("ImagemURL");

                    b.Property<string>("Nome");

                    b.Property<string>("Observacoes");

                    b.Property<string>("PoderesConcedidos");

                    b.Property<string>("Setor");

                    b.Property<string>("Sistema");

                    b.Property<string>("Superior");

                    b.Property<string>("Usuario");

                    b.HasKey("FormularioId");

                    b.ToTable("Formularios");
                });
#pragma warning restore 612, 618
        }
    }
}
