// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMulticel.Repository;

namespace ProMulticel.Repository.Migrations
{
    [DbContext(typeof(ProMulticelContext))]
    partial class ProMulticelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProMulticel.Domain.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataFormulario");

                    b.Property<string>("Filial");

                    b.Property<string>("ImagemURL");

                    b.Property<string>("Observacoes");

                    b.Property<string>("PoderesConcedidos");

                    b.Property<string>("Sistema");

                    b.HasKey("Id");

                    b.ToTable("Formularios");
                });

            modelBuilder.Entity("ProMulticel.Domain.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Setor");

                    b.Property<string>("Superior");

                    b.Property<string>("Usuario");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ProMulticel.Domain.FuncionarioFormulario", b =>
                {
                    b.Property<int?>("FormularioId");

                    b.Property<int?>("FuncionarioId");

                    b.HasKey("FormularioId", "FuncionarioId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("FuncionarioFormularios");
                });

            modelBuilder.Entity("ProMulticel.Domain.FuncionarioFormulario", b =>
                {
                    b.HasOne("ProMulticel.Domain.Formulario", "Formulario")
                        .WithMany("FuncionarioFormularios")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProMulticel.Domain.Funcionario", "Funcionario")
                        .WithMany("FuncionarioFormularios")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
